### ISSUE TITLE
Consultation Request profile

### ISSUE THREAD

**Issue by AlexBaumberg** [Outburn-IL/IL-DGMC-IG#10]
Attached is an example used for validation.

Validation exceptions:

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "value",
            "diagnostics": "5001",
            "details": {
                "text": "Value is 'Organization' but must be 'Practitioner'"
            },
            "expression": [
                "ServiceRequest.performer[1].type"
            ]
        },
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "5001",
            "details": {
                "text": "Profile http://fhir.dgmc.health.gov.il/StructureDefinition/dgmc-cml-consultation-request|0.1.3, Element matches more than one slice - practitioner, organization"
            },
            "expression": [
                "ServiceRequest.performer[0]"
            ]
        },
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "5001",
            "details": {
                "text": "Profile http://fhir.dgmc.health.gov.il/StructureDefinition/dgmc-cml-consultation-request|0.1.3, Element matches more than one slice - practitioner, organization"
            },
            "expression": [
                "ServiceRequest.performer[1]"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "5001",
            "details": {
                "text": "Slicing cannot be evaluated: Could not match discriminator (1) for slice"
            },
            "expression": [
                "ServiceRequest.code.coding[0]"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "5001",
            "details": {
                "text": "Slicing cannot be evaluated: Could not match discriminator (1) for slice"
            },
            "expression": [
                "ServiceRequest.code.coding[1]"
            ]
        },
        {
            "severity": "error",
            "code": "structure",
            "diagnostics": "5001",
            "details": {
                "text": "The type 'Organization' is not a valid Target for this element (must be one of"
            },
            "expression": [
                "ServiceRequest.performer[1]"
            ]
        }
    ]
}
[ServiceRequest.txt](https://github.com/user-attachments/files/16269840/ServiceRequest.txt)

**Comment by mechanik-daniel** [comment]
Solved, the slicing was not configured correctly
