### ISSUE TITLE
Patient profile change request - Incorrect display

### ISSUE THREAD

**Issue by AlexBaumberg** [Outburn-IL/IL-DGMC-IG#11]
Please change afixed value for display from "Hearing impaired" to  "Hearing loss": 

     "url": "http://hl7.org/fhir/StructureDefinition/patient-disability",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "http://snomed.info/sct",
            "code": "15188001",
            **"display": "Hearing loss"**
          }
        ],

**Comment by mechanik-daniel** [comment]
Done
