### ISSUE TITLE
Encounter Namer Movement Profile

### ISSUE THREAD

**Issue by AlexBaumberg** [Outburn-IL/IL-DGMC-IG#12]
Attached is an example used for validation:

1. extension.movement-number definition has been changed in the last core version: 
      - Encounter.hospitalization.extension.movement-number to Encounter.extension.movement-number
       - valuepositiveInt has been changed to valueString

    The mentioned change is not reflected within the "namer movement profile"

2.  Binding to incorrect ValueSet for identifier[nmr-movement].system 

3.   Validation failed with the following exception: 

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "structure",
            "diagnostics": "5001",
            "details": {
                "text": "Slice 'Encounter.identifier:nmr-movement': a matching slice is required, but not found (from http://fhir.health.gov.il/StructureDefinition/dgmc-encounter-movement|0.1.3). Note that other slices are allowed in addition to this required slice"
            },
            "expression": [
                "Encounter"
            ]
        }
    ]
}

[Encounter Movement.txt](https://github.com/user-attachments/files/16272819/Encounter.Movement.txt)

**Comment by mechanik-daniel** [comment]
1. It is reflected: `* extension[movement-number].valueString 1..1` (I didn't touch this). If you still see a problem, open it as a separate issue and provide details
2. The binding was to a VS that didn't exist. I created the VS and the binding works now
3. Validation now passes without errors (but there are warnings to look at)
