### ISSUE TITLE
Encounter Chameleon

### ISSUE THREAD

**Issue by AlexBaumberg** [Outburn-IL/IL-DGMC-IG#13]
Attached is an example used for validation.

Validation exceptions:
[Encounter CML.txt](https://github.com/user-attachments/files/16272895/Encounter.CML.txt)

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "5001",
            "details": {
                "text": "Wrong whitespace in Display Name 'קבלה' for http://fhir.dgmc.health.gov.il/CodeSystem/cml-medical-record-type#2. Valid display is 'קבלה ' (for the language(s) '--')"
            },
            "expression": [
                "Encounter.identifier[1].type.coding[0].display"
            ]
        },
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "5001",
            "details": {
                "text": "Wrong whitespace in Display Name 'קבלה' for http://fhir.dgmc.health.gov.il/CodeSystem/cml-medical-record-type#2. Valid display is 'קבלה ' (for the language(s) '--')"
            },
            "expression": [
                "Encounter.type[0].coding[0].display"
            ]
        },
        {
            "severity": "error",
            "code": "structure",
            "diagnostics": "5001",
            "details": {
                "text": "Encounter.identifier:cml-medical-record: max allowed = 1, but found 2 (from http://fhir.health.gov.il/StructureDefinition/dgmc-encounter-cml|0.1.3)"
            },
            "expression": [
                "Encounter"
            ]
        },
        {
            "severity": "error",
            "code": "structure",
            "diagnostics": "5001",
            "details": {
                "text": "Slice 'Encounter.type:cml-medical-record-type': a matching slice is required, but not found (from http://fhir.health.gov.il/StructureDefinition/dgmc-encounter-cml|0.1.3). Note that other slices are allowed in addition to this required slice"
            },
            "expression": [
                "Encounter"
            ]
        }
    ]
}

**Comment by mechanik-daniel** [comment]
Validation passes after my previous round of corrections
