### ISSUE TITLE
Encounter Namer Case

### ISSUE THREAD

**Issue by AlexBaumberg** [Outburn-IL/IL-DGMC-IG#14]
Attached is an example used for validation.

Validation exceptions: (two of them are coming from terminology services...)

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "code-invalid",
            "diagnostics": "5001",
            "details": {
                "text": "Error from https://tx.fhir.org//r4: Error: A definition for the value Set 'http://fhir.health.gov.il/ValueSet/patient-admit-source-moh' could not be found\r\n"
            },
            "expression": [
                "Encounter.hospitalization.admitSource"
            ]
        },
        {
            "severity": "error",
            "code": "code-invalid",
            "diagnostics": "5001",
            "details": {
                "text": "Error from https://tx.fhir.org//r4: Error: A definition for the value Set 'http://fhir.health.gov.il/ValueSet/patient-visit-reason-moh' could not be found\r\n"
            },
            "expression": [
                "Encounter.reasonCode[0]"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "5001",
            "details": {
                "text": "Slicing cannot be evaluated: Could not match discriminator (1) for slice"
            },
            "expression": [
                "Encounter.type[0]"
            ]
        },
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "5001",
            "details": {
                "text": "Slicing cannot be evaluated: Could not match discriminator (1) for slice"
            },
            "expression": [
                "Encounter.type[0]"
            ]
        }
    ]
}
[Encounter Case.txt](https://github.com/user-attachments/files/16273166/Encounter.Case.txt)

**Comment by mechanik-daniel** [comment]
Validation passes now, not clear which of the changes I made fixed it but it's valid now (except for some warnings)
