### ISSUE TITLE
New  CodeSystem & ValueSet  (patient-visitor-type)

### ISSUE THREAD

**Issue by AlexBaumberg** [Outburn-IL/IL-DGMC-IG#9]
Please create new CodeSystem and ValueSet

CodeSystem URI:  http://fhir.dgmc.health.gov.il/cs/patient-visitor-type
ValueSet URI:  http://fhir.dgmc.health.gov.il/ValueSet/patient-visitor-type
Binding: Encounter Namer Case.subject.extension[visitor-type].valueCodeableConcept.coding
Binding strength: extensible

List of Codes:

1 | אזרח ישראלי
2 | צה"ל   - חילים
4 | תייר   / תושב חוץ
5 | תושב   שטחים
7 | עובד   זר
8 | ילדי   עובד זר
9 | תיירות   מרפא
10 | או"ם
11 | משרד   הבטחון
12 | דייר   רחוב
13 | עובד   זר עם אשרה
14 | שבוי
15 | תושב   ארעי
16 | פליט
17 | שוטר
99 | אחר

**Comment by mechanik-daniel** [comment]
Done, but I've changed the binding so it's on the CodeableConcept itself and not on the Coding
